Repository codesquad-member-2020/issue-tracker-04, pull requests merged in 2020-06, with the labels that each got.

#20 [#19] Emojis, Photos VO 오류를 해결한다.
  BE/src/main/java/com/codesquad/issue04/domain/issue/Comment.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Emoji.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Photo.java
  BE/src/main/java/com/codesquad/issue04/service/TestService.java
  BE/src/main/resources/db/migration/V1__CreateTable.sql
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/TestServiceTest.java
Labels: BE, BE-페어

#24 이슈 모델 컨트롤러 구현 - 필터 기능
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/IssueStateController.swift
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTrackerTests/FakeData.swift
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
Labels: iOS

#31 이슈 작성 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Constants.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIView+RoundedBorders.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormView.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListDataSource.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/NewIssue/NewIssueView.swift
  iOS/IssueTracker/IssueTracker/NewIssue/NewIssueViewController.swift
Labels: iOS

#34 이슈 목록 다중 선택 및 이동 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/IssueListDataSource.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
Labels: iOS

#33 [#32] 깃허브 OAuth 로그인 기능을 구현한다.
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/issue-tracker-04.iml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  BE/.gitignore
  BE/.idea/compiler.xml
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/logs/dev_log.log.2020-06-14.0.gz
  BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
  BE/src/main/java/com/codesquad/issue04/config/auth/CustomOAuth2UserService.java
  BE/src/main/java/com/codesquad/issue04/config/auth/SecurityConfig.java
  BE/src/main/java/com/codesquad/issue04/config/dto/OAuthAttributes.java
  BE/src/main/java/com/codesquad/issue04/config/dto/SessionUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/Role.java
  BE/src/main/java/com/codesquad/issue04/domain/user/User.java
  BE/src/main/java/com/codesquad/issue04/domain/user/UserRepository.java
  BE/src/main/java/com/codesquad/issue04/service/LoginService.java
  BE/src/main/java/com/codesquad/issue04/utils/GithubProperties.java
  BE/src/main/java/com/codesquad/issue04/web/controller/TestController.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/AccessTokenRequestDto.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1__CreateTable.sql
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/LoginServiceTest.java
  iOS/README.md
Labels: BE

#51 Label, Milestone, Issue 읽기 기능
  BE/logs/dev_log.log.2020-06-15.0.gz
  BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
  BE/src/main/java/com/codesquad/issue04/config/auth/SecurityConfig.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Comment.java
  BE/src/main/java/com/codesquad/issue04/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue04/service/IssueService.java
  BE/src/main/java/com/codesquad/issue04/service/LabelService.java
  BE/src/main/java/com/codesquad/issue04/service/LoginService.java
  BE/src/main/java/com/codesquad/issue04/service/MilestoneService.java
  BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue04/web/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue04/web/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueDetailResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/LabelDetailResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/LabelOverviewDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/LabelOverviewResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/MilestoneResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/milestone/MilestoneResponseDto.java
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issue04/service/LabelServiceTest.java
  BE/src/test/java/com/codesquad/issue04/service/MilestoneServiceTest.java
  BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
  BE/src/test/java/com/codesquad/issue04/web/controller/LabelControllerTest.java
  BE/src/test/java/com/codesquad/issue04/web/controller/MilestoneControllerTest.java
Labels: BE

#57 1주차 피드백을 반영하여 빈 사용자에 Null Object Pattern을 적용한다.
  BE/src/main/java/com/codesquad/issue04/config/auth/CustomOAuth2UserService.java
  BE/src/main/java/com/codesquad/issue04/config/dto/OAuthAttributes.java
  BE/src/main/java/com/codesquad/issue04/config/dto/SessionUser.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Comment.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/milestone/AbstractMilestone.java
  BE/src/main/java/com/codesquad/issue04/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue04/domain/milestone/NullMilestone.java
  BE/src/main/java/com/codesquad/issue04/domain/user/AbstractUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/NullUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/RealUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/UserRepository.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueDetailResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewDto.java
  BE/src/test/java/com/codesquad/issue04/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
Labels: BE

#65 모델 상태 관리 기본틀 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailView.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/CommentCollection.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueCollection.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueListModelController.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueModelController.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueStateController.swift
  iOS/IssueTracker/IssueTracker/ModelController/UserModelController.swift
Labels: iOS

#66 이슈의 열린 상태, 닫힌 상태를 추가하고 이를 바탕으로 필터링하는 API를 제공한다.
  BE/build.gradle
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Status.java
  BE/src/main/java/com/codesquad/issue04/service/IssueService.java
  BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/ResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/error/ErrorResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueDetailResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/LabelOverviewResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/label/MilestoneResponseDtos.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/milestone/MilestoneResponseDto.java
  BE/src/main/resources/db/migration/V1__CreateTable.sql
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
Labels: BE

#67 이슈와 유저에 할당자 매핑을 추가한다.
  BE/logs/dev_log.log.2020-06-17.0.gz
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/user/NullUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/RealUser.java
  BE/src/main/java/com/codesquad/issue04/domain/user/UserRepository.java
  BE/src/main/java/com/codesquad/issue04/service/UserService.java
  BE/src/main/java/com/codesquad/issue04/web/controller/UserController.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/user/AllAuthorsResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/user/AuthorDto.java
  BE/src/test/java/com/codesquad/issue04/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issue04/service/UserServiceTest.java
Labels: BE-페어

#61 이슈 CRUD 및 이슈 목록 다중 선택 구현
  iOS/.git_commit_template
  iOS/.gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker.xcscheme
  iOS/IssueTracker/IssueTracker/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  iOS/IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Constants.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIView+RoundedBorders.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailView.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueInfoViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueInfoViewController.xib
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormView.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueCell.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListDataSource.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListTableView.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListTableViewDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/NavigationBarButtonFactory.swift
  iOS/IssueTracker/IssueTracker/IssueList/NavigationController.swift
  iOS/IssueTracker/IssueTracker/IssueTracker.xcdatamodeld/.xccurrentversion
  iOS/IssueTracker/IssueTracker/IssueTracker.xcdatamodeld/IssueTracker.xcdatamodel/contents
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/CommentCollection.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueCollection.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueListModelController.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueModelController.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueStateController.swift
  iOS/IssueTracker/IssueTracker/ModelController/UserModelController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTrackerTests/FakeData.swift
  iOS/IssueTracker/IssueTrackerTests/Info.plist
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
Labels: iOS

#78 이슈를 추가하고 존재하는 이슈의 제목을 수정하며 삭제할 수 있다.
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue04/service/IssueService.java
  BE/src/main/java/com/codesquad/issue04/service/UserService.java
  BE/src/main/java/com/codesquad/issue04/utils/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/IssueCreateRequestDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/IssueDeleteRequestDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/IssueUpdateRequestDto.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1__CreateTable.sql
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
Labels: BE

#81 Issue와 Comments 관계를 일급 콜렉션으로 묶는다.
  BE/src/main/java/com/codesquad/issue04/domain/issue/Comments.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueDetailResponseDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewDto.java
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
Labels: BE

#87 모델 상태관리
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Comment/CommentCell.swift
  iOS/IssueTracker/IssueTracker/Comment/CommentDataSource.swift
  iOS/IssueTracker/IssueTracker/Common/Constants.swift
  iOS/IssueTracker/IssueTracker/Common/GenericTableViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Common/Observer.swift
  iOS/IssueTracker/IssueTracker/Common/PageTitleLabel.swift
  iOS/IssueTracker/IssueTracker/Constants.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIViewController+ChildViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/IssueInfoViewController.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormView.swift
  iOS/IssueTracker/IssueTracker/IssueForm/IssueFormViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueCell.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListDataSource.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListTableViewDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/CommentCollection.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueCollection.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueListModelController.swift
  iOS/IssueTracker/IssueTracker/ModelController/IssueModelController.swift
  iOS/IssueTracker/IssueTrackerTests/FakeData.swift
  iOS/IssueTracker/IssueTrackerTests/IssueListModelControllerTests.swift
  iOS/IssueTracker/IssueTrackerTests/IssueModelControllerTests.swift
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
  iOS/IssueTracker/IssueTrackerTests/ObserverProtocolTests.swift
Labels: iOS

#89 이슈에 마일스톤과 라벨을 추가하고 삭제할 수 있다.
  BE/src/main/java/com/codesquad/issue04/config/WebConfig.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/Comment.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/Photo.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Labels.java
  BE/src/main/java/com/codesquad/issue04/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue04/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue04/domain/user/RealUser.java
  BE/src/main/java/com/codesquad/issue04/service/IssueService.java
  BE/src/main/java/com/codesquad/issue04/service/LabelService.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/CommentDeleteRequestDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/CommentRequestDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/CommentUpdateRequestDto.java
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issue04/service/LabelServiceTest.java
Labels: BE

#90 필터와 리스트 ViewController 추가
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Constants.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueFilterViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/NavigationController.swift
  iOS/IssueTracker/IssueTracker/ListViewController.swift
  iOS/IssueTracker/IssueTracker/MainTabBarController.swift
Labels: iOS

#94 [BE] feat : 필터별 검색을 위한 최종 API
  BE/logs/dev_log.log.2020-06-23.0.gz
  BE/src/main/java/com/codesquad/issue04/Issue04Application.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/Comment.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Comments.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Labels.java
  BE/src/main/java/com/codesquad/issue04/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue04/domain/user/RealUser.java
  BE/src/main/java/com/codesquad/issue04/service/IssueService.java
  BE/src/main/java/com/codesquad/issue04/utils/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issue04/utils/Filter.java
  BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue04/web/dto/request/FilterParamRequestDto.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueOverviewResponseDtos.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V2__InsertData.sql
  BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
Labels: BE

#102 네트워크 API 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/CommentCollection.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueCollection.swift
  iOS/IssueTracker/IssueTracker/Model/Model.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTracker/Network/APILoader.swift
  iOS/IssueTracker/IssueTracker/Network/CRUDEndpoint.swift
  iOS/IssueTracker/IssueTracker/Network/Endpoint.swift
  iOS/IssueTracker/IssueTracker/Network/Endpoints.swift
  iOS/IssueTracker/IssueTracker/Network/IssueLoader.swift
  iOS/IssueTracker/IssueTracker/Network/URLSession+request.swift
  iOS/IssueTracker/IssueTrackerTests/APILoaderTests.swift
  iOS/IssueTracker/IssueTrackerTests/EndpointTests.swift
Labels: iOS

#100 마일스톤 삭제 기능을 정상적으로 구현하도록 수정한다.
  BE/src/main/java/com/codesquad/issue04/config/SwaggerConfig.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Assignees.java
  BE/src/main/java/com/codesquad/issue04/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue04/service/MilestoneService.java
  BE/src/main/java/com/codesquad/issue04/web/dto/response/issue/IssueDetailResponseDto.java
  BE/src/main/resources/db/migration/V1__CreateTable.sql
Labels: BE
